workspace:
  base: /go
  path: .

pipeline:
  build:
    image: golang
    commands:
      - ls -l /go
      - ls -l /go/src
      - ls -l /go/src/maestro
      - go get github.com/gorilla/mux
      - go get gopkg.in/ldap.v2
      - go get gopkg.in/yaml.v2
      - go get golang.org/x/net/context
      - go get github.com/docker/docker/api
      - go get github.com/docker/libcompose/docker
      - go get github.com/docker/libcompose/docker/ctx
      - go get github.com/docker/libcompose/project
      - go get github.com/docker/libcompose/project/options
      - go get github.com/jasonlvhit/gocron
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o maestro maestro

  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/maestro
    tag: latest
    file: Dockerfile

  notif:
    image: no-cloud.fr/drone/xmpp
    jid: ${XMPP_JID}
    password: ${XMPP_PASSWORD}
    to_jid: ${XMPP_TO}

