pipeline:
  build:
    image: golang
    env:
      - GOPATH=/drone
    commands:
      - go get github.com/gorilla/mux
      - go get gopkg.in/ldap.v2
      - go build

  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/maestro
    tag: latest
    file: Dockerfile
