workspace:
  base: /go
  path: src/maestro

pipeline:
  build:
    image: golang
    commands:
      - go get github.com/gorilla/mux
      - go get gopkg.in/ldap.v2
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o maestro

  publish:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/maestro
    tag: latest
    file: Dockerfile
