version: '2'

services:
  traefik:
    image: emilevauge/traefik
    container_name: traefik_test
    ports:
      - 81:80
      - 444:443
    command:
      - --web=false
      - --docker
      - --docker.domain=domain.local
      - --acme=true
      - --acme.storage=/etc/traefik/acme/acme.json
      - --acme.entrypoint=https
      - --acme.email={{ADMIN_MAIL}}
      - --acme.domains={{DOMAINS}}
      - --acme.ondemand=true
      - --entryPoints=Name:https Address::443 TLS
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --defaultentrypoints=http,https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/traefik/acme
    labels:
      - traefik.enable=false

volumes:
  acme:
    driver: local
